# golangci-lint configuration
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - errorlint
    - exhaustive
    - nilerr
    - gocheckcompilerdirectives
    - revive
    - misspell
    - usestdlibvars
    - predeclared
    - copyloopvar
    - gocritic
    - unparam
    - gosec
    - prealloc
    - testifylint
    - paralleltest