# golangci-lint configuration for v2
version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - errorlint
    - exhaustive
    - nilerr
    - gocheckcompilerdirectives
    - revive
    - gofumpt
    - goimports
    - misspell
    - usestdlibvars
    - predeclared
    - copyloopvar
    - gocritic
    - unparam
    - gosec
    - prealloc
    - testifylint
    - paralleltest

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude:
    - vendor
    - testdata